baseURL = "https://domyson.github.io"
languageCode = "zh-cn"
title = "æœèŠ±å¤•æ‹¾"
theme = "github-style"
GoogleAnalytics = "G-V23G8H27BQ"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Treasure"
description = "æ— å…³è¿Ÿæš®ï¼Œä¸é—®ç¿»è¦†."
github = "domyson"
#   facebook = "MeiK2333"
#   twitter = "MeiK2333"1
#   linkedin = "MeiK2333"
#   instagram = "MeiK2333"
#tumblr = "MeiK2333"
email = "cnmlgbbg@hotmail.com"
url = "https://domyson.github.io"
keywords = "computer tech"
rss = true

userStatusEmoji = "ğŸ˜€"
favicon = "/images/avatar.png"
avatar = "/images/avatar.png"
location = "China"

GtmId = "G-V23G8H27BQ"

enableGitalk = true

[params.gitalk]
clientID = "258cd417c7c5b85f68e3"
clientSecret = "4fd96cf3d02ea5bf11e9c29b159e2041557493e6"
repo = "domyson.github.io"
owner = "domyson"
admin = ["domyson"]
id = "location.pathname"
labels = "gitalk"
perPage = 15
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false

[[params.links]]
title = "Link"
href = "https://github.com/domyson"
#   [[params.links]]
#     title = "Link2"
#     href = "https://meik2333.com"
#     icon = "https://meik2333.com/images/avatar.png"

# https://mephisto.cc/zh-tw/tech/hugo-adsense/


lastmod = false
#[frontmatter]
#lastmod = [":fileModTime", ":default"]


[params]
  enableSearch = true

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false