baseURL = "https://domyson.github.io"
languageCode = "zh-cn"
title = "æ»¡èˆ¹æ¸…æ¢¦å‹æ˜Ÿæ²³"
theme = "github"
#googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Treasure"
  description = "æ— å…³è¿Ÿæš®ï¼Œä¸é—®ç¿»è¦†."
  github = "domyson"
#   facebook = "MeiK2333"
#   twitter = "MeiK2333"1
#   linkedin = "MeiK2333"
#   instagram = "MeiK2333"
  #tumblr = "MeiK2333"
  email = "cnmlgbbg@hotmail.com"
  url = "https://domyson.github.io"
  keywords = "computer tech"
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/images/avatar.png"
  location = "China"
  #enableGitalk = true

#   [params.gitalk]
#     clientID = "Your client ID" 
#     clientSecret = "Your client secret" 
#     repo = "repo"
#     owner = "MeiK2333"
#     admin = "MeiK2333"
#     id = "location.pathname"
#     labels = "gitalk"
#     perPage = 15
#     pagerDirection = "last"
#     createIssueManually = true
#     distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/domyson"
#   [[params.links]]
#     title = "Link2"
#     href = "https://meik2333.com"
#     icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]